### ISSUE TITLE
Update BoxBilling links

### ISSUE THREAD

**Issue by BelleNottelling** [PayFast/mod-boxbilling#1]
Hello, I am one of the (new) developers for BoxBilling and I noticed that the links on your website are outdated. 
They still point to BoxBilling.com which we don't currently have control of and it's full of outdated information.

Would it be possible to get these links changed to our GitHub? https://github.com/boxbilling/boxbilling

I noticed the old links on these pages:
https://www.payfast.co.za/integration/shopping-carts/boxbilling
-and- 
https://support.payfast.co.za/portal/en/kb/articles/how-do-i-integrate-payfast-with-boxbilling

Thank you

**Comment by bruce-atkinson** [comment]
Hi @BelleNottelling, this has been noted and will be updated along with release v1.2.0 (#2)
